MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.13'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
c_compiler_version:        # [osx and x86_64]
  - 13                     # [osx and x86_64]
cxx_compiler_version:      # [osx and x86_64]
  - 13                     # [osx and x86_64]
