# qt-main uses 13 for their OSX build, so we need to use it during cross-comp
c_compiler_version:        # [osx and arm64]
  - 13                     # [osx and arm64]
cxx_compiler_version:      # [osx and arm64]
  - 13                     # [osx and arm64]
