{% set version = "4.8.3" %}
{% set build = 0 %}

# Adapted from https://github.com/conda-forge/vtk-feedstock/blob/main/recipe/meta.yaml
# PySide6 is lower priority than PyQt5 for backward compat (e.g., with matplotlib,
# mayavi, etc.) until the ecosystem updates
{% set build = build + 100 %}  # [build_variant == "noqt"]
{% set build = build + 200 %}  # [build_variant == "pyside6"]
{% set build = build + 300 %}  # [build_variant == "pyqt"]

package:
  name: mayavi
  version: {{ version }}

source:
  fn: mayavi-{{ version }}.tar.gz
  url: https://github.com/enthought/mayavi/archive/{{ version }}.tar.gz
  sha256: eb7f46952d4786008ed4f272172bec475fcdcb988f5e1c5405daea9d41955cef

build:
  number: {{ build }}
  entry_points:
    - mayavi2 = mayavi.scripts.mayavi2:main
    - tvtk_doc = tvtk.tools.tvtk_doc:main
  # C99 issue on macOS, see failures in
  # https://github.com/conda-forge/mayavi-feedstock/pull/80

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - vtk-base                            # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - vtk-base
    - traitsui
    - apptools
  run:
    - python
    - {{ pin_compatible('vtk-base', max_pin='x.x') }}
    - traitsui
    - pyface
    - apptools
    - envisage
    - pyqt         # [build_variant == "pyqt"]
    - pyside6      # [build_variant == "pyside6"]
    - setuptools

test:
  requires:
    - pip
    - pytest
  commands:
    - mayavi2 --help
    - xvfb-run pytest -v --pyargs mayavi  # [build_variant != "noqt" and linux]
    - pytest -v --pyargs mayavi  # [not linux]
    - xvfb-run pytest -v --pyargs tvtk  # [build_variant != "noqt" and linux]
    - pytest -v --pyargs tvtk  # [not linux]
  imports:
    - tvtk
    - tvtk.array_ext
    - mayavi

about:
  home: https://github.com/enthought/mayavi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Mayavi scientific data 3-dimensional visualizers
  doc_url: http://docs.enthought.com/mayavi/mayavi
  dev_url: https://github.com/enthought/mayavi

extra:
  recipe-maintainers:
    - msarahan
    - grlee77
    - dfroger
    - cadair
    - larsoner
