{% set version = "4.8.2" %}
{% set build = 4 %}

# Adapted from https://github.com/conda-forge/vtk-feedstock/blob/main/recipe/meta.yaml
# PySide6 is lower priority than PyQt5 for backward compat (e.g., with matplotlib,
# mayavi, etc.) until the ecosystem updates
{% set build = build + 100 %}  # [build_variant == "pyside6"]
{% set build = build + 200 %}  # [build_variant == "pyqt"]
{% set build_string = '{}_py{}h{}_{}'.format(build_variant, CONDA_PY, PKG_HASH, build) %}

package:
  name: mayavi
  version: {{ version }}

source:
  fn: mayavi-{{ version }}.tar.gz
  url: https://github.com/enthought/mayavi/archive/{{ version }}.tar.gz
  sha256: a78eb7512948d9484c0ba7b1fdeab088f9f4a32ca32862a0b8e8d2b63ad83eb2
  patches:
    # Using Cython 3.0.10 and NumPy 2.0 installed rather than Cython 3.0.8
    - cython.patch

build:
  number: {{ build }}
  string: {{ build_string }}
  entry_points:
    - mayavi2 = mayavi.scripts.mayavi2:main
    - tvtk_doc = tvtk.tools.tvtk_doc:main
  # C99 issue on macOS, see failures in
  # https://github.com/conda-forge/mayavi-feedstock/pull/80
  skip: True  # [py<39 and osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - vtk                                    # [build_platform != target_platform]
    - qt-main                                # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython
    - numpy
    - vtk
    - qt-main
    - traitsui
    - apptools
  run:
    - python
    - vtk
    - traitsui
    - pyface
    - apptools
    - envisage
    - pyqt  # [build_variant == "pyqt"]
    - pyside6  # [build_variant == "pyside6"]
    - setuptools

test:
  commands:
    - mayavi2 --help
  imports:
    - tvtk
    - tvtk.array_ext
    - mayavi

about:
  home: https://github.com/enthought/mayavi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Mayavi scientific data 3-dimensional visualizers
  doc_url: http://docs.enthought.com/mayavi/mayavi
  dev_url: https://github.com/enthought/mayavi

extra:
  recipe-maintainers:
    - msarahan
    - grlee77
    - dfroger
    - cadair
    - larsoner
